### ISSUE TITLE
Quero ajudar

### ISSUE THREAD

**Issue by leonampd** [ieducar/ieducar#14]
Estive hoje no pub do PHPSP e, foi falado desse projeto. Confesso que não lembro o nome das pessoas que falaram sobre ele mas estou disposto a ajudar no que for possível. Acho que o primeiro passo é atualizar o projeto.

**Comment by farribeiro** [comment]
Este projeto não se encontra mais aqui, embora o projeto original não existe mais e outros lideram o remanescente do projeto e recentemente comentei com o líder do projeto e me disse que foi movido[1] para o site Software Público Brasileiro conforme comentado na Issue ~https://github.com/educacaoitajai/erudio/issues/3~ (broken link) e no PR https://github.com/ieducar/ieducar/pull/10#issuecomment-330429252

Fiz uma busca no repositório do SPB e ~não encontrei seu projeto~, carece de mais buscas. Como era um projeto da Prefeitura de Itajaí/SC, surgiu um fork[2]:

[1] https://softwarepublico.gov.br/gitlab/groups/i-educar
[2] https://github.com/educacaoitajai/erudio

**Comment by MarceloCajueiro** [comment]
Bom dia,

Em breve vamos voltar a usar esse projeto do github, que nos dá mais liberdade para discutir e subir melhorias da comunidade.

Vamos criar um planejamento o quanto antes e compartilhar com a comunidade para unir forças.

**Comment by leonampd** [comment]
@MarceloCajueiro n lembro se era vc q estava no pub ontem mas enfim. Imagino que mtas coisas mas to disposto a ajudar no que for possível.

**Comment by MarceloCajueiro** [comment]
Não era eu não @leonampd. Era o @fernandosjp.

Vou fazer um texto sobre quais serão os próximos passos e voltamos a falar @leonampd. Vai ser muito bom ter a sua ajuda.

**Comment by leonampd** [comment]
Show! eu sugeri pro @fernandosjp criar um board dentro do projeto, o github projects. É legal pra dar visibilidade do que precisa ser feito e qual a prioridade disso xD

**Comment by farribeiro** [comment]
Recomendo desativar os repositórios redundantes, como este abaixo, que se diz parte do projeto:

https://github.com/portabilis/ieducar

Além de reaproveitar os PRs

**Comment by MarceloCajueiro** [comment]
@farribeiro sim, vamos fazer isso de fato, deixar apenas o oficial.

**Comment by fernandosjp** [comment]
@leonampd fui eu que apresentei lá no PHPSP. Super legal esse encontro da comunidade PHP! A empresa que está a frente hoje do i-Educar é a Portabilis, onde o @MarceloCajueiro é líder de tecnologia. Eles estão a frente dessa mudança para o desenvolvimento diretamente no repositório aberto! Vai ser essencial ter a ajuda de mais pessoas!

**Comment by farribeiro** [comment]
Também recomendo troca de expertise com o fork erudio.

**Comment by leonampd** [comment]
Show de bola @fernandosjp @MarceloCajueiro. Já dei um `watch` no projeto. Vou acompanhar o projeto e ajudar no que eu conseguir.

**Comment by MarceloCajueiro** [comment]
@leonampd nesse momento inicial vamos precisar de ajuda na modelagem da arquitetura que o projeto vai seguir. 

Por ser um projeto com código legado e sem muitos padrões, precisamos começar a organizar isso tudo.

**Comment by lucassantos61** [comment]
Seguindo , issue do @leonampd  tbm estou interressado em ajudar

**Comment by MarceloCajueiro** [comment]
Criei um slack depois que o @leonampd deu a ideia: https://join.slack.com/t/i-educar/shared_invite/enQtMzEyMTk5ODg5NTA1LTIzMDYzMTEzYWJkOWIyOWZiOTM2ZWEyOTc3Yjk2N2NkYzA4MmUzM2VmNDU4MDNkNWIyY2RiMjYwZjI1NmEwYWQ

**Comment by farribeiro** [comment]
Vou verificar a reabertura do meu PR

**Comment by farribeiro** [comment]
Sugestão! Reavaliar as PR fechadas.

**Comment by farribeiro** [comment]
Issue https://github.com/ieducar/ieducar/issues/18

**Comment by eder1985** [comment]
Também quero ajudar, pessoal. Trabalhei 6 anos na secretaria de educação do meu município e atualmente sou analista de TI na Dataprev. Tenho conhecimento em JS, HTML5, CSS3 (LESS e SASS) e outras tecnologias web. Segue meu linkedin: https://www.linkedin.com/in/eder-nogueira-7398213a/

**Comment by farribeiro** [comment]
Issue https://github.com/ieducar/ieducar/issues/31

**Comment by farribeiro** [comment]
Há tem definido alguma data para liberação do projeto?nnPois estamos em meados de Abril ainda não tem algum anuncio.

**Comment by farribeiro** [comment]
O que pedia é data...

**Comment by MarceloCajueiro** [comment]
Bom dia,

Atualizei o README com uma data mais concreta: https://github.com/ieducar/ieducar/commit/8433623f78a6d240e1adf08b0ee395e48542c857

**Comment by farribeiro** [comment]
Agora temos uma meta

**Comment by MarceloCajueiro** [comment]
Vamos postergar a liberação do código para o dia 4 de junho.

Estamos finalizando diversos ajustes para o censo escolar e achamos prudente subir tudo junto para evitar conflitos, já que vamos mudar o nosso jeito de trabalhar para trabalhar direto no repositório da comunidade.

**Comment by farribeiro** [comment]
Liberado? Acho que temos algumas outras dúvidas as sanar caso da Issue https://github.com/portabilis/i-educar/pull/203

**Comment by farribeiro** [comment]
Quero atentar, PRINCIPALMENTE, ao ponto 1 e 2 do `README.md` a pedido de juniorghr:

```
### Etapas iniciais deste processo

1. Liberar na versão Comunidade as principais melhorias feitas pela Portabilis nos últimos anos;
2. A Portabilis irá mudar seu fluxo de trabalho passando a desenvolver diretamente no repositório da Comunidade;
```
