### ISSUE TITLE
Slack para o projeto

### ISSUE THREAD

**Issue by leonampd** [ieducar/ieducar#15]
Dado que é um projeto que vai passar por várias mãos. Seria legal ter um canal de comunicação mais próximo. Tem sido comum alguns projetos criarem uma conta no slack para falar do projeto. Por isso to abrindo essa, issue. Pra deixar como sugestão mesmo. Imagino que seria uma boa maneira de aproximar os envolvidos.

**Comment by MarceloCajueiro** [comment]
@leonampd você acha que um canal no telegram supre? nós já temos um lá.

**Comment by leonampd** [comment]
@MarceloCajueiro hummm.. n sei. Eu particularmente não curto muito o telegram pra esse tipo de coisa. Acho q a experiência fica um tanto ruim quando o número de pessoas é grande e o volume de mensagens aumenta mto. O que eu vejo de mais legal no slack em relação ao telegram:

- Canais. Dá pra segmentar a conversa por assunto. Inclusive fechar alguns deles para assuntos mais delicados, se necessário
- Threads: As vezes surgem dois assuntos paralelos e com as threads as conversas ficam mais organizadas

Lembrando que é opinião pessoal xD

**Comment by MarceloCajueiro** [comment]
Concordo com você. Segue o link: https://join.slack.com/t/i-educar/shared_invite/enQtMzEyMTk5ODg5NTA1LTIzMDYzMTEzYWJkOWIyOWZiOTM2ZWEyOTc3Yjk2N2NkYzA4MmUzM2VmNDU4MDNkNWIyY2RiMjYwZjI1NmEwYWQ
