### ISSUE TITLE
Fundir repositórios SPB e Github

### ISSUE THREAD

**Issue by farribeiro** [ieducar/ieducar#18]
Discussão de planejamento para fundir os códigos dos dois repositório.

Devido a reativação, do projeto no github organizar para fusão.

Issue original https://github.com/ieducar/ieducar/issues/14#issuecomment-364403135 e PR https://github.com/ieducar/ieducar/pull/10#issuecomment-330429252

## Mentions
@giustin 
@carolinesalib

**Comment by leonampd** [comment]
Pq precisamos fundir os códigos @farribeiro? Tem features diferentes em cada um dos repos? Olhando superficialmente, eu arriscaria dizer que faz mais sentido somente substituir o código que está nesse repo pelo mais atual.

**Comment by farribeiro** [comment]
Para torná-lo unico. Este projeto no qual abri issue é datado em toro de 2011 enquanto no SPB a ultima atividade é de 4 dias, a minha recomendação é atualizar esta base com a do SPB, unificando projetos.

**Comment by MarceloCajueiro** [comment]
Olá!

Antes de sairmos criando um backlog temos que marcar uma conversa pra todos
ficarem na mesma página.

Podemos fazer isso semana que vem? Topam um hangouts na quarta?

**Comment by farribeiro** [comment]
Somente sou um entusiasta que gostaria de sugerir algumas melhorias, nada mais profundo.

**Comment by leonampd** [comment]
@MarceloCajueiro 

Concordo contigo. Só n acho que o hangout seja a melhor opção. Acho que um bom `README` e um projects bem alinhado seja o caminho. Você pode criar issues e classificar com `help wanted` e aí todos os interessados podem dar suas contribuições. De fato, se criarmos issues a rodo aqui vamos acabar tendo um série de coisas sem valor agregado e imagino que esse n seja o objetivo. Tecnologia por tecnologia não é o caminho :)

**Comment by MarceloCajueiro** [comment]
Isso aí @leonampd.

Eu vou escrever um texto explicando tudo certinho assim conseguimos caminhar para o `README` bem escrito e o `help wanted`.

**Comment by MarceloCajueiro** [comment]
Sincronizei com o repositório do SPB. @carolinesalib ao invés de sincronizar com o da Portabilis, vamos sincronizar com esse agora, por favor. :D

**Comment by carolinesalib** [comment]
Oi, @MarceloCajueiro! 

Ciente.

**Comment by farribeiro** [comment]
Houve problemas na sincronização do repositório, pois nos commits estão referenciando errado e sim aos issues que estão no SPB

**Comment by MarceloCajueiro** [comment]
Não é problema. A questão é que os commtis lá no SPB referenciavam issues
do gitlab. Aqui vão referenciar errado mesmo pois não tem os mesmos
códigos. Não tem o que fazer acredito eu.

**Comment by farribeiro** [comment]
Será que não consegue trazer eles para cá?

**Comment by MarceloCajueiro** [comment]
Sim, vamos tentar isso. Hoje o Tiago, CEO da Portabilis já é o coordenador
da comunidade i-educar. A ideia é manter tudo no github, mas veremos em
breve.
