### ISSUE TITLE
Troca de expertise com o fork - Erudio.

### ISSUE THREAD

**Issue by farribeiro** [ieducar/ieducar#20]
Discussão para troca de expertise com o fork do i-educar, o Erudio. https://github.com/educacaoitajai/erudio

Issue original https://github.com/educacaoitajai/erudio/issues/3

## Mentions

@educacaoitajai

**Comment by farribeiro** [comment]
Como @educacaoitajai fechou os fontes, mesmo que temporariamente, não estou mais considerando um projeto genuinamente opensource.

Resta somente esta solução como no âmbito educacional. Ao agrado dos mantedor do projeto encerrar esse issue

@MarceloCajueiro ok?
@fernandosjp ok?

**Comment by MarceloCajueiro** [comment]
Ok.

Em qui, 29 de mar de 2018 10:19 AM, Fábio Rodrigues Ribeiro <
notifications@github.com> escreveu:
