### ISSUE TITLE
Utilização de framework REACTJS/ANGULARJS/VUEJS

### ISSUE THREAD

**Issue by farribeiro** [ieducar/ieducar#22]
Discussão para troca de framework JS

**Comment by lucassantos61** [comment]
Qual framework está sendo utilizado atualmente ? Ou não há nenhum ?

**Comment by farribeiro** [comment]
Pelo que vi, é o jquery... Mas deve uma versão bem antiga, digamos o projeto tem uma grande estrada! Porém também precisa um trato na UI

**Comment by leonampd** [comment]
Faz sentido, nesse momento, discutir sobre isso? Pergunto pq tecnologia por tecnologia acho que não resolve o problema de fato. Acho que se for possível deixar funcional mesmo q com uma tecnologia antiga faz mais sentido nesse momento.

faz sentido?

**Comment by farribeiro** [comment]
Sim, claro que cabe... É como migrar do PHP das cavernas a algo como o que o Facebook escreve (com PHP, a exemplo do que foi hip-hop PHP) ou até nodejs (queridinha de hoje)

**Comment by leonampd** [comment]
O que eu quero dizer é que num primeiro momento n me parece agregar valor trocar a tecnologia. Mudar uma tecnologia pela outra demanda tempo e dedicação para garantir que tudo funcionava antes continua funcionando. Entendo que a modernização é necessária mas pro cliente final pouco importa a versão da linguagem, o que importa é funcionar e resolver o problema/necessidade.

**Comment by farribeiro** [comment]
Eu só peço que atualizem para o que há de melhor nos dias atuais, de preferencia na mesma linguagem, para sair da obsolência de códigos legados. Pode fazer até um roadmap de como fazer a transição

**Comment by lucassantos61** [comment]
Eu acho que nesse momento não é o ideial para definir o framework JS , pois como já e utilizado alguma coisa de JS o trabalho que vai gerar um trabalho que pode quebrar o desenvolvimento do projeto , do meu ponto de vista acho que é melhor tomar essa deceisão em outro momento. Afinal atualização de codigo legado sempre é mais trabalhosa do que se imagina.

**Comment by farribeiro** [comment]
Eu sei lá Portabilis tah correndo o roadmap, e ela fará um enorme commit. Não está aceitando PR, provavelmente está discutindo isso. A abertura de dialogo com seus usuários e entusiasta em participar de processos decisórios. seria mais interessante. Penso assim, que se deve manter aberto o debate e reaberto até periodicamente para novos rumos & tendencias.

Lá no slack deixei uma leitura... A catedral e o bazar (Eric Raymond)

https://github.com/farribeiro/catb-ptbr/releases/download/v1.40.1a1/catb-ptbr.pdf

**Comment by MarceloCajueiro** [comment]
Esse não é o momento realmente para esse tipo de discussão. Por isso não estou gastando energia respondendo e fechando issues, pois já foi alertado que o momento que a Portabilis passa é de organização para trazer grandes patches para a comunidade. Depois disso iremos discutir sobre pontos de tecnologia como aliado na transformação do software para os clientes (todas as redes municipais do País), mas já adianto que a última coisa que vamos falar é em framework JS.

Vou fechar para evitar discussão atoa.
