### ISSUE TITLE
Atualizar o README e criar um help wanted

### ISSUE THREAD

**Issue by MarceloCajueiro** [ieducar/ieducar#24]
Precisamos organizar o que deve ser feito no projeto, contando as novidades e como as pessoas podem nos ajudar.

**Comment by farribeiro** [comment]
Que tal começar com um pequeno todo list?

**Comment by giustin** [comment]
Oi @farribeiro cc @MarceloCajueiro !

Readme atualizado com mais informações do projeto e definição dos próximos passos (roadmap).

Obrigado pela contribuição e vamos mantendo contato por aqui.
