### ISSUE TITLE
Bloqueio do branch master para commits diretos

### ISSUE THREAD

**Issue by leonampd** [ieducar/ieducar#31]
Vi que alguns, dos últimos commits do projeto foram feitos direto no branch `master`. Daí fica a sugestão de bloquear o branch para commits diretos garantindo que todo o código que está nele foi testado/revisado etc e que está estável. Dessa forma toda alteração precisaria ser feita através de um pull request e, por consequência, por revisão e testes.

**Comment by farribeiro** [comment]
É uma boa pratica, eu sei, mas não interfere ao fluxo de trabalhos, pode se commitar assim quando se trata de algo de extrema importância, um bugfix

**Comment by leonampd** [comment]
Discordo já que toda vez que escrevemos código estamos sujeitos a inserir novos bugs, por exemplo. Commitar diretamente no branch principal não permitiria, entre outras coisas, um bom processo de code review, testes automatizados utilizando ferramentas como travis-ci etc etc. Também seria possível utilizar outras ferramentes que avaliariam, a cada request, a saúde do código através de análise estática. Por isso, IMHO, não mandar código direto para o branch principal vai muito além de boa prática.

**Comment by farribeiro** [comment]
Então pergunta... Por que se abriu o canal do Slack... Enfeite?

**Comment by lflimeira** [comment]
Mas em casos excepcionais não podem ocorrer códigos ruins ou que podem causar bugs?

N faz sentido quebrar o flow em nenhum caso. Se está quebrando, talvez não esteja clara a importância do mesmo.

**Comment by farribeiro** [comment]
Por isso são excepcionais... deve ser acionado em ultimo recurso.

**Comment by leonampd** [comment]
Nesses casos como vc garantiria a estabilidade do código, @farribeiro, já que um bugfix pode precisar de outro bugfix na sequência? O famoso _na minha máquina funciona_

Além disso, dado que o projeto está no github como ter um histórico controlado do que é incluído? Toda adição/remoção/alteração no código precisa ter um contexto muito bem detalhado dos motivos, impactos etc etc. Commitar direto no branch principal n provê isso. Só provê desordem, na verdade.

Inclusive, casos excepcionais são exemplos de desordem.

**Comment by farribeiro** [comment]
Se seguir ao menos este cheatsheet:

https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html

**Comment by lflimeira** [comment]
Mas no git-flow não cita nada sobre mandar direto na master em casos excepicionais. :pensive:

**Comment by farribeiro** [comment]
Não se chama hotfix... perceba que do master altera e devolve direto ao master e develop

> - Os hotfixes surgem da necessidade de agir imediatamente sobre uma situação indesejada na versão de produção ativa
> - Pode ser criado a partir da tag correspondente no branch master que indica a versão em produção.

**Comment by leonampd** [comment]
Git flow **!==** commit direto no master

Git flow:

```
git checkout master
git pull origin master
git checkout -b hotfix-xpto
code....
git commit
git push origin hotfix-xpto
Pull request...
git checkout master
git pull origin master
git merge hotfix-xpto
git push origin master
```

Má prática:

```
git checkout master
git pull origin master
code...
git push origin master
```

**Comment by lflimeira** [comment]
" **Finalizar um hotfix**
Ao finalizar um hotfix ele é mesclado tanto no develop quanto no master. Além disso, o merge no master é etiquetado."

Veja que ele cria uma branch de hotfix e depois mergeia ela na master, em nenhum momento é criado um commit diretamente na master.

**Comment by farribeiro** [comment]
Mas note... o branch é... APAGADO! Só deixa o tag. Se for um só eke faz cherry-pick

**Comment by lflimeira** [comment]
Cara... Se vc apaga o Branch quer dizer que vc criou ele e não fez o commit direto na master mas sim na branch, correto?

O fato dela não existir mais, não quer dizer que vc fez o commit na master, logo faz sentido o que o @leonampd está propondo de bloquear a branch master.

**Comment by farribeiro** [comment]
Ao mover como um cherry-pick ou rebase ele mescla na história do master, nada de novo ramo

**Comment by lflimeira** [comment]
O que vc está dizendo só valida o fato de bloquear a master, repare que para mesclar na história da master, vc tem que ter o que mesclar antes (branch do hotfix). Bloquear a master n vai impossibilitar que seja feito rebase nela.

![image](https://user-images.githubusercontent.com/7549765/36916977-429c7dd0-1e34-11e8-8635-1b569453d0f5.png)

**Comment by farribeiro** [comment]
A respeito de bloquear o master independe desta tema que estamos focado, obviamente isso deve ser tomada pela liderança do projeto!

@MarceloCajueiro 
@giustin

**Comment by lflimeira** [comment]
A discussão toda era por esse motivo (que vc disse de não bloquear a master para fazer commit de hotfix direto na mesma), teria sido bem mais simples ter feito isso desde o começo. :pensive:

**Comment by farribeiro** [comment]
Recomendo entrar ao canal do slack para assunto que não seja bugfix do projeto

**Comment by farribeiro** [comment]
https://join.slack.com/t/i-educar/shared_invite/enQtMzEyMTk5ODg5NTA1LTIzMDYzMTEzYWJkOWIyOWZiOTM2ZWEyOTc3Yjk2N2NkYzA4MmUzM2VmNDU4MDNkNWIyY2RiMjYwZjI1NmEwYWQ

**Comment by farribeiro** [comment]
@MarceloCajueiro@giustin

**Comment by farribeiro** [comment]
Novamente foi aplicado commit diretamente no master, vide[1]

Para histórico, dois grupos telegram especializados em gitlab[2] e git[3]

[1] commit https://github.com/ieducar/ieducar/commit/895a5a446db2c31f04b2aca323653387f7603530
[2] https://t.me/gitlabbr
[3] https://t.me/GitBrasil

@leonampd
@lflimeira
