### ISSUE TITLE
Substituir Apache pelo Nginx

### ISSUE THREAD

**Issue by edisonrocha** [ieducar/ieducar#35]
Pessoal, tenho um servidor rodando alguns sites wordpress com o nginx e gostaria de saber se é possível rodar o I-Educar no nginx. Tem algum workaround disso?

Obrigado.

**Comment by farribeiro** [comment]
No momento o ieducar está em fase de organização por parte do core team. Possivelmente não terá uma resposta mais direta quanto a minha. 

Com certeza tem, mas fica a cargo de quem irá implantar o sistema.

Se prive a usar discussões de suporte neste canal, apenas para relatar bugs e funcionalidades, a respeito suporte comunitário visite https://i-educar.slack.com , caso esclarecido por gentileza encerrar esta discussão

**Comment by edisonrocha** [comment]
Muito obrigado, @farribeiro ! Vou encerrar a issue aqui.

**Comment by MarceloCajueiro** [comment]
@farribeiro é isso mesmo. Muito obrigado.
